package com.southasia.boxoffice;
import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import com.squareup.picasso.Picasso;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Karthik on 5/3/2015.
 * Generates custom adapter to display trailer thumbnail(generated by Thumbnails.java) and short description.
 */
public class CustomAdapter extends ArrayAdapter<String>{
    private List<Trailer> listOfTrailers;
    private Context context;
    public CustomAdapter(Context context, String[] videoIds, List<Trailer> trailers) {
        super(context, R.layout.custom_row, videoIds);
        listOfTrailers = trailers;
        this.context = context;
    }

    //returns custom view for the position
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        LayoutInflater trailerSuggestionInflater = LayoutInflater.from(getContext());
        View customView = trailerSuggestionInflater.inflate(R.layout.custom_row, parent, false);
        String videoID = getItem(position);
        String shortDescription = shortDescription(videoID);
        TextView trailerSuggestionText = (TextView) customView.findViewById(R.id.trailerText);
        ImageView thumbnailImage = (ImageView) customView.findViewById(R.id.trailerThumbnail);
        if(shortDescription!=null) {
            trailerSuggestionText.setText(shortDescription);
        }
        else {
            trailerSuggestionText.setText("Description not available");
        }
        Picasso.with(context).load("http://img.youtube.com/vi/" + videoID + "/default.jpg").into(thumbnailImage);
       return customView;
    }
    //Gets the shortdescription for the associated videoid returns null if failed.
    private String shortDescription(String videoID)
    {
        for(Trailer trailer:listOfTrailers)
        {
            if(trailer.getVideoID().equals(videoID))
            {
                return trailer.getShortDescription();
            }
        }
        return null;
    }
}
